name: Check code style

on:
  # push:
  #   branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]
  workflow_dispatch:

jobs:
  check_style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Check if the code adheres to the standard style
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        chmod +x scripts/check_style_ci.sh
        ./scripts/check_style_ci.sh $DISCORD_WEBHOOK
